  const starNames = [
    "Alpheratz",
    "Caph",
    "Algenib",
    "Pearce's Star",
    "Citadelle",
    "Deneb Kaitos Shemali",
    "Alrial",
    "Ankaa",
    "Felixvarela",
    "Fulu",
    "Shedar",
    "Diphda",
    "Alnitham",
    "Cocibolca",
    "Kuton",
    "Achird",
    "van Maanen's Star",
    "Castula",
    "Navi",
    "Nenque",
    "Marfak",
    "Wurren",
    "Dheneb",
    "Mirach",
    "Emiw",
    "Marfak",
    "Revati",
    "Adhil",
    "Al Naymat",
    "Bélénos",
    "Ruchbah",
    "Thail",
    "Alpherg",
    "Titawin",
    "Achernar",
    "Nembus",
    "Torcular",
    "Baten Kaitos",
    "Mothallah",
    "Mesarthim",
    "Segin",
    "Sheratan",
    "Alrescha",
    "Almach",
    "Hamal",
    "Mizan",
    "Al Kaff al Jidhmah",
    "Misam al Thurayya",
    "Mira",
    "Sadr al Kaitos",
    "Polaris",
    "Buna",
    "Barani",
    "Koleon",
    "Kaffaljidhma",
    "Koeia",
    "Lilii Borea",
    "Al Butain",
    "Nushagak",
    "Bharani",
    "Miram",
    "Angetenar",
    "Azha",
    "Acamar",
    "Gorgonea Secunda",
    "Menkar",
    "Ayeyarwady",
    "Aludhi",
    "Menkar",
    "Gorgonea Tertia",
    "Algol",
    "Althiba",
    "Misam",
    "Gorgonea Quarta",
    "Botein",
    "Dalim",
    "Zibal",
    "Angetenar",
    "Intan",
    "Mirfak",
    "Ran",
    "Tupi",
    "Rana",
    "Atik",
    "Celaeno",
    "Electra",
    "Taygeta",
    "Maia",
    "Asterope",
    "Sterope",
    "Merope",
    "Alcyone",
    "Atlas",
    "Pleione",
    "Atik",
    "Zaurak",
    "Menkib",
    "Nembus",
    "Beid",
    "Keid",
    "Beemim",
    "Prima Hyadum",
    "Alkalbain",
    "Secunda Hyadum",
    "Beemim",
    "Ain",
    "Chamukuy",
    "Hoggar",
    "Beemim",
    "Theemin",
    "Aldebaran",
    "Sceptrum",
    "Bidelman's Peculiar Star",
    "Tabit",
    "Mouhoun",
    "Al Taj",
    "Al Kumm",
    "Manica",
    "Hassaleh",
    "Hind's Crimson Star",
    "Kursi al Jauzah",
    "Almaaz",
    "Saclateni",
    "Haedus",
    "Cursa",
    "Mago",
    "Kapteyn's Star",
    "Alhiba",
    "Rigel",
    "Capella",
    "Saif al Jabbar",
    "Bellatrix",
    "Elnath",
    "Nihal",
    "Thabit",
    "Mintaka",
    "The Ruby Star",
    "Arneb",
    "Heka",
    "Meissa",
    "Trapezium",
    "Becklin's Star",
    "Mizan Batil",
    "Hatysa",
    "Alnilam",
    "Bubup",
    "Tianguan",
    "Phact",
    "Andrews' star",
    "Alnitak",
    "Kursi al Jabbar",
    "Saiph",
    "Wazn",
    "Arsh al Jauzah",
    "Betelgeuse",
    "Menkalinan",
    "Mahasim",
    "Propus",
    "Elkurud",
    "Amadioha",
    "Propus",
    "Red Rectangle",
    "Furud",
    "Mirzam",
    "Tejat",
    "Canopus",
    "Dolones",
    "Lucilinburhuc",
    "Nucatai",
    "Lusitânia",
    "Plaskett's Star",
    "Alhena",
    "Nosaxa",
    "Mebsuta",
    "Sirius",
    "Alzirr",
    "Nervia",
    "Udra",
    "Isis",
    "Adhara",
    "Citalá",
    "Unurgunite",
    "Al Zara",
    "Muliphein",
    "Mekbuda",
    "Wezen",
    "Bernes 135",
    "Wasat",
    "Aludra",
    "Propus",
    "Gomeisa",
    "Luyten's Star",
    "Castor",
    "Markab",
    "Jishui",
    "Procyon",
    "Ceibo",
    "Pollux",
    "Tapecue",
    "Azmidi",
    "Naos",
    "Tureis",
    "Regor",
    "Tegmine",
    "Tarf",
    "Násti",
    "Piautos",
    "Avior",
    "Alsciaukat",
    "Muscida",
    "Minazal",
    "Minchir",
    "Muscida",
    "Gakyid",
    "Museida",
    "Meleph",
    "Asellus Borealis",
    "Asellus Australis",
    "Alsephina",
    "Zubanah",
    "Ashlesha",
    "Copernicus",
    "Stribor",
    "Acubens",
    "Talitha",
    "Alkaphrah",
    "Suhail",
    "Alhaud",
    "Nahn",
    "Miaplacidus",
    "Markeb",
    "Aspidiske",
    "Markeb",
    "Al Minlear al Asad",
    "Alphard",
    "Intercrus",
    "Ukdah",
    "Alterf",
    "Illyrian",
    "Kalausi",
    "Ukdah",
    "Al Sharasif",
    "Subra",
    "Algenubi",
    "Natasha",
    "Zhang",
    "Rasalas",
    "Felis",
    "Bibhā",
    "Al Jabhah",
    "Regulus",
    "Adhafera",
    "Tania Borealis",
    "Algieba",
    "Tania Australis",
    "Klemola's Star",
    "Macondo",
    "Praecipua",
    "Chalawan",
    "Alkes",
    "Merak",
    "Lalande 21185",
    "Dubhe",
    "Dingolay",
    "Al Sharasif",
    "Zosma",
    "Chertan",
    "Zubrah",
    "Innes' Star",
    "Abt's Star",
    "Hunahpú",
    "Hunahpú",
    "Alula Australis",
    "Alula Borealis",
    "Labr",
    "Moriah",
    "Giausar",
    "Formosa",
    "Sagarmatha",
    "Przybylski's Star",
    "Uklun",
    "Flegetonte",
    "Taiyangshou",
    "Denebola",
    "Zavijava",
    "Aniara",
    "Groombridge 1830",
    "Phecda",
    "Tonatiuh",
    "Alchiba",
    "Minkar",
    "Imai",
    "Megrez",
    "Gienah",
    "Zaniah",
    "Ginan",
    "Tupã",
    "Acrux",
    "Al Dafirah",
    "Algorab",
    "Kissin",
    "Gacrux",
    "Funi",
    "Chara",
    "Kraz",
    "Muhlifain",
    "Porrima",
    "La Superba",
    "Tianyi",
    "Mimosa",
    "Polaris Galacticus Borealis",
    "Alioth",
    "Taiyi",
    "Minelauva",
    "Cor Caroli",
    "Vindemiatrix",
    "Apami-Atsa",
    "Diadem",
    "Mizar",
    "Spica",
    "Alcor",
    "Dofida",
    "Liesma",
    "Heze",
    "Alkaid",
    "Muphrid",
    "Alnair",
    "Hadar",
    "Thuban",
    "Menkent",
    "Kang",
    "Asellus Tertius",
    "Popper's Star",
    "Arcturus",
    "Syrma",
    "Asellus Secundus",
    "Xuange",
    "Khambaliya",
    "Bidelman's Helium Variable Star",
    "Asellus Primus",
    "Elgafar",
    "Proxima",
    "Seginus",
    "Toliman",
    "Rigil Kentaurus",
    "Men",
    "Rijl al Awwa",
    "Izar",
    "Mönch",
    "Merga",
    "Zubenelgenubi",
    "Kochab",
    "Zubenelgenubi",
    "Arcalís",
    "Baekdu",
    "KeKouan",
    "Ke Kwan",
    "Zuben Elakribi",
    "Nekkar",
    "Brachium",
    "Aulad Alnathlat",
    "Zuben Hakrabi",
    "Thiba",
    "Zubeneschamali",
    "Pherkad Minor",
    "Nikawiy",
    "Pherkad",
    "Alkalurops",
    "Edasich",
    "Nusakan",
    "Alphecca",
    "Nasak Yamani",
    "Zubenelhakrabi",
    "Karaka",
    "Ceginus",
    "Akfa Farkadain",
    "Unukalhai",
    "Nasak Shamiya",
    "Variabilis Coronae",
    "Gudja",
    "Iklil",
    "Fang",
    "Blaze Star",
    "Dschubba",
    "Grafias",
    "Acrab",
    "Jabhat Acrabi",
    "Marsic",
    "Kamui",
    "Jabbah",
    "Sharjah",
    "Yed Prior",
    "Anwa Farkadain",
    "Yed Posterior",
    "Hunor",
    "Alniyat",
    "Athebyne",
    "Cujam",
    "Timir",
    "Antares",
    "Kornephoros",
    "Ogma",
    "Marfik",
    "Rosalíadecastro",
    "Paikauhale",
    "Saik",
    "Rutilicus",
    "Circitores",
    "Atria",
    "Larawag",
    "Xamidimura",
    "Pipirima",
    "Mahsati",
    "Grafias",
    "Rapeto",
    "Alrakis",
    "Aldhibah",
    "Sabik",
    "Rasalgethi",
    "Sarin",
    "Guniibuu",
    "Inquill",
    "Aggia",
    "Garafsa",
    "Rastaban",
    "Maasym",
    "Lesath",
    "Choo",
    "Adfar Aldib",
    "Kuma",
    "Yildun",
    "Kuma",
    "Shaula",
    "Rasalhague",
    "Al Dhih",
    "Sargas",
    "Dziban",
    "Dsiban",
    "Mula",
    "Cebalrai",
    "Iron Star",
    "Alruba",
    "Cervantes",
    "Girtab",
    "Muliphen",
    "Fuyue",
    "Vanant",
    "Grumium",
    "Eltanin",
    "Barnard's Star",
    "Sinistra",
    "Alava",
    "Pincoya",
    "Nash",
    "Alnasl",
    "Polis",
    "Hamalwarid",
    "Aldhiba",
    "Kaus Media",
    "Alahakan",
    "Alasia",
    "Kaus Australis",
    "Al Athfar",
    "Fafnir",
    "Kaus Borealis",
    "Vega",
    "Xihe",
    "Double Double",
    "Nasr Alwaki",
    "Tweedledee and Tweedledum",
    "Namalsadirah",
    "Sheliak",
    "Ainalrami",
    "Athafi",
    "Nunki",
    "Kaveh",
    "Alya",
    "Sulafat",
    "Deneb al Okab Borealis",
    "Ascella",
    "Manubrij",
    "Okab",
    "Al Thalimain Prior",
    "Meridiana",
    "Albaldah",
    "Altais",
    "Aladfar",
    "Al Kiladah",
    "Gumala",
    "Fawaris",
    "Tais",
    "Belel",
    "Arkab Prior",
    "Sika",
    "Arkab Posterior",
    "Rukbat",
    "Almizan",
    "Anser",
    "Albireo",
    "Uruk",
    "Alsafi",
    "Campbell's Star",
    "Al Thalimain Posterior",
    "Sham",
    "Fawaris",
    "Tarazed",
    "Tyl",
    "Altair",
    "Tarazed",
    "Libertas",
    "Alshain",
    "Terebellum",
    "Terebellum",
    "Terebellum",
    "Terebellum",
    "Al Aghnam",
    "Phoenicia",
    "Chechia",
    "Prima Giedi",
    "Revenant of the Swan",
    "Algedi",
    "Alshat",
    "Dabih Minor",
    "Dabih",
    "Sadr",
    "Peacock",
    "Okul",
    "Al Kidr",
    "Ruchba",
    "Ruchba",
    "Aldulfin",
    "Rotanev",
    "Persian",
    "Sualocin",
    "Deneb",
    "Al Ukud",
    "Kabalfird",
    "Wei",
    "Aljanah",
    "Al Salib",
    "Albali",
    "Albulan",
    "Musica",
    "Arm",
    "Bessel's Star",
    "Polaris Australis",
    "Albulaan",
    "Solaris",
    "Kitalpha",
    "Alderamin",
    "Yen",
    "Alfirk",
    "Sadalsuud",
    "Kastra",
    "Bunda",
    "Sāmaya",
    "Nashira",
    "Azelfafage",
    "Bosona",
    "The Garnet Star",
    "Enif",
    "Castula",
    "Deneb Algedi",
    "Aldhanab",
    "Itonda",
    "Sadalmulk",
    "Kurhah",
    "Fum al Faras",
    "Sadalmelik",
    "Alnair",
    "Biham",
    "Ancha",
    "Sadachbia",
    "Seat",
    "Lionrock",
    "Kruger 60",
    "Sadaltager",
    "Al Kalb al Rai",
    "Fum al Hui",
    "Situla",
    "Homam",
    "Sadalmatar",
    "Tiaki",
    "Matar",
    "Babcock's Star",
    "Sadalnazi",
    "Suudalnujum",
    "Sadalbari",
    "Hydor",
    "Skat",
    "Helvetios",
    "Fomalhaut",
    "Scheat",
    "Fumalsamakah",
    "Markab",
    "Ebla",
    "Salm",
    "Alkarab",
    "Veritate",
    "Poerava",
    "Errai",
    "Axólotl"
  ];

const randomStarName = () => {
  const name = starNames[Math.floor(Math.random() * starNames.length)];
  const kebabCase = name.toLowerCase().replace(' ', '-');
  return kebabCase;
}

module.exports = {
  randomStarName
}